"""
Options Flow Monitor - End-to-end Python agent

What this file contains
- A single-file end-to-end solution you can run locally or in Docker.
- Connects to a third-party options trade API (Polygon.io example implemented).
- Runs a rule-based suspicious-trade detector (10 rules you specified).
- Schedules checks at fixed intervals (default 30 minutes) using APScheduler.
- Persists results to SQLite and saves CSVs for flagged trades.
- Sends alerts via Slack webhook (optional) and writes logs.
- Helper to generate Dockerfile, requirements.txt, and sample .env file.

How to use
1) Create a directory and put this file there.
2) Create a .env file (see sample generated by --init or look at README below):
   - POLYGON_API_KEY=...
   - PROVIDER=polygon    # or tradier (placeholders)
   - SYMBOLS=ORCL,NBIS,AAPL
   - POLL_INTERVAL_MIN=30
   - SLACK_WEBHOOK_URL=...
   - ALERT_THRESHOLD=2   # suspicious score threshold to alert
3) Install requirements:
   pip install -r requirements.txt
   (or run: python options-flow-monitor-e2e.py --init to create files)
4) Run:
   python options-flow-monitor-e2e.py

Notes
- Polygon API endpoint /v3/trades/options/{symbol} is used as example; adapt if your provider differs.
- This script is ready-to-run but will need your API key and webhook.

"""

import os
import sys
import time
import json
import logging
import argparse
from datetime import datetime, timedelta
from typing import List

import requests
import pandas as pd
import sqlite3

# Scheduler
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.executors.pool import ProcessPoolExecutor

# Load env variables easily
from dotenv import load_dotenv

load_dotenv()

# ------------------------ Configuration ------------------------
POLYGON_API_KEY = os.getenv('POLYGON_API_KEY', '').strip()
PROVIDER = os.getenv('PROVIDER', 'polygon').lower()
SYMBOLS = [s.strip().upper() for s in os.getenv('SYMBOLS', 'ORCL,NBIS').split(',') if s.strip()]
POLL_INTERVAL_MIN = int(os.getenv('POLL_INTERVAL_MIN', '30'))
SLACK_WEBHOOK = os.getenv('SLACK_WEBHOOK_URL', '').strip()
ALERT_THRESHOLD = int(os.getenv('ALERT_THRESHOLD', '2'))  # score above which to alert
DB_PATH = os.getenv('DB_PATH', 'options_monitor.db')
OUTPUT_DIR = os.getenv('OUTPUT_DIR', './outputs')
LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO')

os.makedirs(OUTPUT_DIR, exist_ok=True)

# Configure logging
logging.basicConfig(
    level=LOG_LEVEL,
    format='%(asctime)s [%(levelname)s] %(message)s',
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(os.path.join(OUTPUT_DIR, 'monitor.log'))
    ]
)
logger = logging.getLogger('options-monitor')

# ------------------------ Utilities ------------------------

def fetch_options_trades_polygon(symbol: str, limit: int = 500) -> pd.DataFrame:
    """Fetch recent options trades for a symbol from Polygon.io (example).
    You must have POLYGON_API_KEY environment variable set.
    This endpoint /v3/trades/options/{symbol} returns results in 'results' list.
    """
    if not POLYGON_API_KEY:
        raise RuntimeError('POLYGON_API_KEY not set in environment')

    url = f"https://api.polygon.io/v3/trades/options/{symbol}"
    params = {
        'limit': limit,
        'apiKey': POLYGON_API_KEY
    }
    logger.debug('Fetching Polygon trades for %s', symbol)
    r = requests.get(url, params=params, timeout=30)
    r.raise_for_status()
    data = r.json().get('results', [])
    if not data:
        return pd.DataFrame()
    df = pd.json_normalize(data)
    # Normalize common fields expected in downstream detection function
    # These mappings may differ per provider. We attempt to map common names.
    mappings = {
        'sym': 'Symbol',
        'price': 'Trade',
        'size': 'Size',
        'conditions': 'Conditions',
        'exchange': 'Exchange',
        'timestamp': 'Timestamp',
        'option_type': 'Type',
        'strike_price': 'Strike',
        'expiration_date': 'Expires'
    }
    df.rename(columns=mappings, inplace=True)

    # Convert timestamp (Polygon gives epoch micros) to readable
    if 'Timestamp' in df.columns:
        try:
            # polygon v3 may give 'participant_timestamp' or 'timestamp' as ms
            df['Timestamp'] = pd.to_datetime(df['Timestamp'], unit='ms', utc=True).dt.tz_convert('US/Eastern')
        except Exception:
            pass

    # Ensure required columns exist with defaults if missing
    for col in ['Symbol','Trade','Size','Type','Strike','Expires','Timestamp']:
        if col not in df.columns:
            df[col] = None

    # Add placeholder Bid/Ask/Mid if provider not returning them (best-effort)
    if 'bid' in df.columns:
        df['Bid'] = pd.to_numeric(df['bid'], errors='coerce')
    else:
        df['Bid'] = pd.NA
    if 'ask' in df.columns:
        df['Ask'] = pd.to_numeric(df['ask'], errors='coerce')
    else:
        df['Ask'] = pd.NA
    df['Mid'] = df[['Bid','Ask']].astype(float).mean(axis=1)

    # Premium and Open Int not always available; leave as NaN if missing
    for c in ['premium','open_interest']:
        if c in df.columns:
            df[c.capitalize()] = pd.to_numeric(df[c], errors='coerce')

    # Normalize Type values
    if 'Type' in df.columns:
        df['Type'] = df['Type'].map(lambda x: str(x).capitalize())

    return df

# Provider dispatcher - add more providers here if needed
def fetch_trades(symbol: str, provider: str = 'polygon', limit: int = 1000) -> pd.DataFrame:
    if provider == 'polygon':
        return fetch_options_trades_polygon(symbol, limit=limit)
    else:
        raise NotImplementedError(f'Provider {provider} not implemented; extend fetch_trades()')

# ------------------------ Detection Logic ------------------------

def detect_suspicious_trades(df: pd.DataFrame, size_abs_threshold: int = 100) -> pd.DataFrame:
    """Apply the 10-pattern detector to an options trades DataFrame.
    Expects columns: Symbol, Trade, Size, Bid, Ask, Mid, Premium, Open Int, Type, Delta, Expires, Timestamp, Side
    """
    if df.empty:
        return df

    df = df.copy()

    # Normalize numeric fields
    for col in ['Trade','Size','Premium','Open Int','Strike','Delta']:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')
        else:
            df[col] = pd.NA

    # Bid/Ask parsing if strings like '12.60 x 212'
    def parse_price_field(x):
        try:
            if pd.isna(x):
                return pd.NA
            if isinstance(x, (int,float)):
                return float(x)
            s = str(x)
            return float(s.split('x')[0].strip())
        except Exception:
            return pd.NA

    df['Bid'] = df.get('Bid', pd.NA).apply(parse_price_field)
    df['Ask'] = df.get('Ask', pd.NA).apply(parse_price_field)
    df['Mid'] = df[['Bid','Ask']].astype(float).mean(axis=1)

    # Per-symbol thresholds (95th percentile)
    size_95 = df['Size'].quantile(0.95) if df['Size'].notna().any() else float('inf')
    premium_95 = df['Premium'].quantile(0.95) if 'Premium' in df.columns and df['Premium'].notna().any() else float('inf')

    # Flags
    df['AggressiveLift'] = df['Trade'] >= df['Ask']
    df['PriceDeviationPct'] = (df['Trade'] - df['Mid']).abs() / df['Mid'] * 100
    df['PriceDeviation'] = df['PriceDeviationPct'] > 5
    df['LargeSize'] = df['Size'] > size_95
    df['LargeSize_abs'] = df['Size'] >= size_abs_threshold
    df['LargePremium'] = df['Premium'] > premium_95
    df['DeepITMCallBuy'] = ((df['Type'].str.lower() == 'call') & (df['Delta'] > 0.7) & (df.get('Side', '').astype(str).str.lower().isin(['ask','buy'])))

    # Repeats - exact matches within +/-15 minutes
    df['RepeatedWithin15m'] = False
    df = df.sort_values('Timestamp')
    for idx,row in df.iterrows():
        try:
            window_start = row['Timestamp'] - pd.Timedelta(minutes=15)
            window_end = row['Timestamp'] + pd.Timedelta(minutes=15)
            mask = (
                (df['Strike']==row['Strike']) &
                (df['Expires']==row['Expires']) &
                (df['Size']==row['Size']) &
                (df['Trade']==row['Trade']) &
                (df['Timestamp'].between(window_start, window_end))
            )
            if mask.sum() > 1:
                df.at[idx,'RepeatedWithin15m'] = True
        except Exception:
            continue

    # Volume vs OI
    df['VolVsOI'] = df['Size'] / df['Open Int'].replace({0: pd.NA})
    df['VolVsOI_flag'] = df['VolVsOI'] > 0.10

    # IV jump: check future rows within 30 minutes for same strike/expiry
    df['IV_jump'] = False
    if 'IV' in df.columns or 'IV_num' in df.columns:
        ivcol = 'IV_num' if 'IV_num' in df.columns else 'IV'
        for idx,row in df.iterrows():
            try:
                if pd.isna(row['Timestamp']) or pd.isna(row.get(ivcol)):
                    continue
                window_end = row['Timestamp'] + pd.Timedelta(minutes=30)
                future = df[(df['Timestamp']>row['Timestamp']) & (df['Timestamp']<=window_end) & (df['Strike']==row['Strike']) & (df['Expires']==row['Expires'])]
                if not future.empty and future.get(ivcol).max() > row.get(ivcol) * 1.05:
                    df.at[idx,'IV_jump'] = True
            except Exception:
                continue

    # Cluster timing: last hour of market (>=15:00 ET assumed)
    df['ClusterLastHour'] = df['Timestamp'].dt.tz_localize(None).dt.time >= datetime.strptime('15:00:00','%H:%M:%S').time()

    # Cross-strike cluster: 3+ unique strikes in +/-10 minute window for buyer-initiated
    df['CrossStrikeCluster'] = False
    for idx,row in df.iterrows():
        try:
            window_start = row['Timestamp'] - pd.Timedelta(minutes=10)
            window_end = row['Timestamp'] + pd.Timedelta(minutes=10)
            window = df[df['Timestamp'].between(window_start, window_end)]
            unique_strikes = window['Strike'].nunique()
            side = str(row.get('Side','')).lower()
            if unique_strikes >= 3 and side in ['ask','buy']:
                df.at[idx,'CrossStrikeCluster'] = True
        except Exception:
            continue

    flags = ['AggressiveLift','PriceDeviation','LargeSize','LargePremium','DeepITMCallBuy','RepeatedWithin15m','VolVsOI_flag','IV_jump','ClusterLastHour','CrossStrikeCluster']
    df['SuspiciousScore'] = df[flags].sum(axis=1).astype(int)

    # Return suspicious rows only
    suspicious = df[df['SuspiciousScore']>0].copy()
    return suspicious

# ------------------------ Persistence & Alerts ------------------------

def init_db(db_path: str = DB_PATH):
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()
    cur.execute('''
        CREATE TABLE IF NOT EXISTS suspicious_trades (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            symbol TEXT,
            strike REAL,
            expires TEXT,
            trade_price REAL,
            size INTEGER,
            premium REAL,
            suspicious_score INTEGER,
            flags TEXT,
            timestamp TEXT,
            inserted_at TEXT
        )
    ''')
    conn.commit()
    conn.close()


def persist_suspicious(suspicious: pd.DataFrame, db_path: str = DB_PATH):
    if suspicious.empty:
        return 0
    conn = sqlite3.connect(db_path)
    rows = []
    for _,r in suspicious.iterrows():
        rows.append((
            r.get('Symbol'),
            float(r.get('Strike')) if not pd.isna(r.get('Strike')) else None,
            str(r.get('Expires')),
            float(r.get('Trade')) if not pd.isna(r.get('Trade')) else None,
            int(r.get('Size')) if not pd.isna(r.get('Size')) else None,
            float(r.get('Premium')) if not pd.isna(r.get('Premium')) else None,
            int(r.get('SuspiciousScore')),
            json.dumps({k: bool(r.get(k)) for k in ['AggressiveLift','PriceDeviation','LargeSize','LargePremium','DeepITMCallBuy','RepeatedWithin15m','VolVsOI_flag','IV_jump','ClusterLastHour','CrossStrikeCluster']}),
            str(r.get('Timestamp')),
            datetime.utcnow().isoformat()
        ))
    cur = conn.cursor()
    cur.executemany('''INSERT INTO suspicious_trades (symbol,strike,expires,trade_price,size,premium,suspicious_score,flags,timestamp,inserted_at)
                       VALUES (?,?,?,?,?,?,?,?,?,?)''', rows)
    conn.commit()
    conn.close()
    return len(rows)


def alert_slack(suspicious: pd.DataFrame, webhook_url: str = SLACK_WEBHOOK):
    if not webhook_url or suspicious.empty:
        return False
    # build text summary - keep concise
    blocks = []
    for _,r in suspicious.head(10).iterrows():
        text = f"*{r.get('Symbol')}* {r.get('Type')} {r.get('Strike')} exp:{r.get('Expires')} \nPrice:{r.get('Trade')} size:{r.get('Size')} score:{int(r.get('SuspiciousScore'))}"
        blocks.append({'type':'section','text':{'type':'mrkdwn','text':text}})
    payload = {'text': f"Suspicious trades detected: {len(suspicious)}","blocks": blocks}
    try:
        resp = requests.post(webhook_url, json=payload, timeout=10)
        resp.raise_for_status()
        logger.info('Slack alerted for %d suspicious trades', len(suspicious))
        return True
    except Exception as e:
        logger.exception('Failed to send slack alert: %s', e)
        return False

# ------------------------ Main monitor job ------------------------

def monitor_once(symbols: List[str] = None):
    symbols = symbols or SYMBOLS
    all_suspicious = []
    for s in symbols:
        try:
            logger.info('Fetching trades for %s', s)
            df = fetch_trades(s, provider=PROVIDER, limit=2000)
            if df is None or df.empty:
                logger.debug('No trades returned for %s', s)
                continue
            # Normalize columns possibly present in polygon output to our expected names
            # If provider returns differently, you may need to map columns here.
            suspicious = detect_suspicious_trades(df)
            count = persist_suspicious(suspicious)
            logger.info('Persisted %d suspicious trades for %s', count, s)
            if not suspicious.empty:
                timestamp = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
                out_csv = os.path.join(OUTPUT_DIR, f'suspicious_{s}_{timestamp}.csv')
                suspicious.to_csv(out_csv, index=False)
                logger.info('Wrote suspicious CSV %s', out_csv)
                all_suspicious.append((s, suspicious))
        except Exception as e:
            logger.exception('Error processing symbol %s: %s', s, e)

    # Aggregate across symbols and alert once
    if all_suspicious:
        combined = pd.concat([t[1] for t in all_suspicious], ignore_index=True)
        # Only alert if max score exceeds threshold
        if combined['SuspiciousScore'].max() >= ALERT_THRESHOLD:
            alert_slack(combined)

# ------------------------ CLI & Helpers ------------------------

def generate_supporting_files(output_dir: str = '.'):
    # requirements
    requirements = """
requests
pandas
python-dotenv
apscheduler
sqlalchemy
"""
    with open(os.path.join(output_dir, 'requirements.txt'), 'w') as f:
        f.write(requirements.strip())

    dockerfile = f"""
FROM python:3.11-slim
WORKDIR /app
COPY . /app
RUN pip install -r requirements.txt
ENV POLL_INTERVAL_MIN={POLL_INTERVAL_MIN}
CMD ["python", "options-flow-monitor-e2e.py"]
"""
    with open(os.path.join(output_dir, 'Dockerfile'), 'w') as f:
        f.write(dockerfile.strip())

    env_sample = f"""
# Sample .env file - copy and edit with your keys
PROVIDER=polygon
POLYGON_API_KEY={POLYGON_API_KEY}
SYMBOLS=ORCL,NBIS
POLL_INTERVAL_MIN={POLL_INTERVAL_MIN}
SLACK_WEBHOOK_URL=
ALERT_THRESHOLD={ALERT_THRESHOLD}
DB_PATH=options_monitor.db
OUTPUT_DIR=outputs
"""
    with open(os.path.join(output_dir, '.env.sample'), 'w') as f:
        f.write(env_sample.strip())

    readme = """
Options Flow Monitor

1) Edit .env.sample and save as .env with your API keys & settings.
2) Install requirements: pip install -r requirements.txt
3) Run: python options-flow-monitor-e2e.py

The application will run once by default, or if you use --daemon it will schedule periodic checks.
"""
    with open(os.path.join(output_dir, 'README.md'), 'w') as f:
        f.write(readme)

    logger.info('Generated requirements, Dockerfile, .env.sample, README in %s', output_dir)


def main(argv=None):
    parser = argparse.ArgumentParser(description='Options Flow Monitor - E2E')
    parser.add_argument('--init', action='store_true', help='Generate requirements, Dockerfile, .env.sample and README')
    parser.add_argument('--run', action='store_true', help='Run monitor once and exit')
    parser.add_argument('--daemon', action='store_true', help='Run as background scheduler polling every POLL_INTERVAL_MIN minutes')
    parser.add_argument('--symbols', type=str, help='Comma-separated symbols to monitor (overrides .env SYMBOLS)')
    args = parser.parse_args(argv)

    if args.init:
        generate_supporting_files(output_dir='.')
        print('Init files generated (requirements.txt, Dockerfile, .env.sample, README.md)')
        return

    if args.symbols:
        symbols = [s.strip().upper() for s in args.symbols.split(',') if s.strip()]
    else:
        symbols = SYMBOLS

    init_db(DB_PATH)

    if args.run:
        monitor_once(symbols)
        return

    if args.daemon:
        # Use APScheduler to run monitor periodically in background
        executors = {
            'default': {'type': 'threadpool', 'max_workers': 5},
            'processpool': ProcessPoolExecutor(max_workers=2)
        }
        scheduler = BackgroundScheduler(executors=executors, timezone='US/Eastern')
        scheduler.add_job(lambda: monitor_once(symbols), 'interval', minutes=POLL_INTERVAL_MIN, next_run_time=datetime.now())
        scheduler.start()
        logger.info('Scheduler started: polling every %s minutes for symbols: %s', POLL_INTERVAL_MIN, symbols)
        try:
            while True:
                time.sleep(10)
        except (KeyboardInterrupt, SystemExit):
            scheduler.shutdown()
            logger.info('Scheduler stopped')
        return

    # Default action: run once
    monitor_once(symbols)

if __name__ == '__main__':
    main()
